### PR TITLE
updated dependencies and workflows

### LINKED ISSUE #11: update dependencies

### PR DESCRIPTION
**Pull request by lukebrdn**
Resolves #11 

It was suggested this would be a good candidate for the new publish process.

### CODE REVIEW

**Comment by carlansley** [comment]
@adcreare looks good to me, but I'll leave it un-reviewed until you get a chance to try the new publish with it

**Comment by adcreare** [comment]
@carlansley I think its working right. tsc is outputting the following index.js and that's what the new publish will produce.


```javascript
"use strict";
// index.ts
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.HASH_NAMESPACE = exports.hash = exports.default = void 0;
/*
 * Copyright (c) 2021 Check Digit, LLC
 *
 * This code is licensed under the MIT license (see LICENSE.txt for details).
 */
var hash_1 = require("./hash");
Object.defineProperty(exports, "default", { enumerable: true, get: function () { return __importDefault(hash_1).default; } });
var hash_2 = require("./hash");
Object.defineProperty(exports, "hash", { enumerable: true, get: function () { return __importDefault(hash_2).default; } });
Object.defineProperty(exports, "HASH_NAMESPACE", { enumerable: true, get: function () { return hash_2.HASH_NAMESPACE; } });
//# sourceMappingURL=index.js.map
```

**Review by adcreare — APPROVED** [review]
LGTM

**Comment by carlansley** [comment]
@adcreare this code unfortunately doesn't work since it's not setting the default export properly.  there needs to be a `module.exports = exports = hash_1` or something like that.

```
> const x = await import('./test.js');  // this has the code as-above
undefined
> x
[Module: null prototype] {
  HASH_NAMESPACE: undefined,
  __esModule: true,
  default: { default: [Getter], hash: [Getter], HASH_NAMESPACE: [Getter] }
}
> 
```

e.g. using it in the above context, `x` should be of type function

**Review by carlansley — CHANGES_REQUESTED** [review]
PR ok, but @adcreare still needs to fix publish

**Comment by adcreare** [comment]
@carlansley I think I've figured it out, we're having issues with our setting of `esModuleInterop: true`


With `esModuleInterop: false` I get the following doing a top level import. 
And we can see that .hash is defined which is what I think we should get
```Javascript
➜  hash git:(update-deps) ✗ # Set "esModuleInterop": false,
➜  hash git:(update-deps) ✗ rm -rf build && npx tsc && node testhis.js
[Module: null prototype] {
  HASH_NAMESPACE: 'f25d4515-fea7-44c7-8baf-f3ca50865e66',
  __esModule: true,
  default: { default: [Getter], hash: [Getter], HASH_NAMESPACE: [Getter] },
  hash: [Function: default_1]
}
------
.hash:  [Function: default_1]
```

This is what the same test harness was giving with out existing tsconfig which matches what you go.
Only default export no hash.. 
I'll do a PR over in typescript-config
```Javascript
➜  hash git:(update-deps) ✗ rm -rf build && npx tsc && node testhis.js
[Module: null prototype] {
  HASH_NAMESPACE: 'f25d4515-fea7-44c7-8baf-f3ca50865e66',
  __esModule: true,
  default: { default: [Getter], hash: [Getter], HASH_NAMESPACE: [Getter] }
}
------
.hash:  undefined
```

**Comment by adcreare** [comment]
Quick update on this PR.
Typescript can't seem to provide the output we want in line with cjs and mjs, so we'll most likely be introducing a bundler that handles that over in typescript-config. I'll update this PR when that is ready.

**Comment by carlansley** [comment]
I'm going to do a new PR for my changes, think it makes sense to squerge this as-is.

**Review by carlansley — APPROVED** [review]

**Review by carlansley — APPROVED** [review]

**Comment by carlansley** [comment]
@lukebrdn needs a label, but otherwise is good to go

**Pull request merged**
